### ISSUE TITLE
Covers with white colors turned red on Discord

### ISSUE THREAD

**Issue by kiramountains** [phin05/discord-rich-presence-plex#101]
I use this primarily for showing my Plexamp listening on Discord, songs with covers that have pure white color get turned red, it's like this on my PC and phone
![image](https://github.com/user-attachments/assets/e8a1c258-d44d-4879-b659-e5d30708314c)
![image](https://github.com/user-attachments/assets/d2113479-4622-404d-bae6-7c682b38e49b)
![image](https://github.com/user-attachments/assets/60bab978-75a2-42d7-9024-4b2de6a7470e)
![image](https://github.com/user-attachments/assets/313601a0-b2c1-4e63-b2b9-8385e85c7d60)

**Comment by phin05** [comment]
Fixed in [v2.10.0](https://github.com/phin05/discord-rich-presence-plex/releases/tag/v2.10.0).
