### ISSUE TITLE
Progress bar not working

### ISSUE THREAD

**Issue by adkeyz** [phin05/discord-rich-presence-plex#102]
Hi, I am using the newest 2.10.0 version and have added "progressMode: Bar" to my config file but it's not displaying the bar and still showing the elapsed time.

I have "remainingTime: false", I tried to remove this line completely but it keeps being added back to the config when running the script.

Am I doing something wrong here? Below is my config.

logging:
  debug: false
  writeToFile: false
display:
  duration: true
  genres: true
  album: true
  year: true
  statusIcon: false
  remainingTime: false
  paused: true
  posters:
    enabled: true
    imgurClientID:
    maxSize: 256
  buttons:
    - label: '{title} on IMDb'
      url: dynamic:imdb
    - label: '{title} on MusicbBainz'
      url: dynamic:musicbrainz
      mediaTypes:
        - track
  progressMode: bar
users:
  - token: 
    servers:
      - name:

**Comment by phin05** [comment]
Are you sure you're using v2.10.0? You should see `Discord Rich Presence for Plex - v2.10.0` when you run the script.

The behaviour you're describing would be exhibited if you were using an older version.

**Comment by adkeyz** [comment]
You were right, I checked the first line of the running script and it was still showing 2.9.0 even though I replaced all the files.

I just deleted everything and set it up from scratch and the bar is now showing.

Completely my fault, sorry!

I do notice that when paused, the bar disappears and the elapsed time shows instead but the time is completely wrong, is this normal?

**Comment by phin05** [comment]
> Completely my fault, sorry!

No worries.

> I do notice that when paused, the bar disappears and the elapsed time shows instead but the time is completely wrong, is this normal?

This is broken on Discord's end. I'm omitting the timestamp in the data sent to Discord while media is paused because it's not possible to make it display a static/frozen timestamp, but Discord is ignoring the omission and displaying a timestamp starting from 0. We'll have to wait for them to fix it. For the time being, you can set `display.paused` to `false` in your config to just hide your Rich Presence while media is paused.

**Comment by FortKnox1337** [comment]
Not sure if you are aware of this but I have noticed that the elapsed, remaining and paused functions do display properly on my mobile app so it looks like the information is being sent to the discord app properly it's just not displaying it on the desktop app for some reason. Either way, I'm using the progress bar which works for both desktop and mobile now :)

**Comment by adkeyz** [comment]
I have also noticed that when you start playing something, the rich presence will start showing the time elapsed for about 10-15 seconds before switching to the bar.

Would it not be possible to still have the rich presence persist while paused without the time instead of just disappearing completely?

I use the below app for YouTube Music which has a rich presence plugin and the progress bar is instant and when paused the rich presence remains but just the progress bar disappears until playback is resumed.

[](https://github.com/th-ch/youtube-music)

Playing:

![playing](https://github.com/user-attachments/assets/8a2f062a-dfd6-44aa-a7a0-7d1ac1070590)


Paused:

![paused](https://github.com/user-attachments/assets/127d92d3-396a-4108-a759-5bd9dc94d141)

**Comment by phin05** [comment]
@FortKnox1337 That's good to know.

@adkeyz 

> I have also noticed that when you start playing something, the rich presence will start showing the time elapsed for about 10-15 seconds before switching to the bar.

I'm not able to reproduce this issue. I always see only the progress bar as long as `display.progressMode` is set to `bar`.

> Would it not be possible to still have the rich presence persist while paused without the time instead of just disappearing completely?

You can do this by setting `display.paused` to `true` in your config. The time is supposed to disappear but it's not doing that because it's broken on Discord's end.

> I use the below app for YouTube Music which has a rich presence plugin and the progress bar is instant and when paused the rich presence remains but just the progress bar disappears until playback is resumed.

I believe the progress bar is disappearing only for yourself. The same thing happens to me with my script. Pause your media and ask someone else if they can see your progress bar.

**Comment by adkeyz** [comment]
> I'm not able to reproduce this issue. I always see only the progress bar as long as display.progressMode is set to bar, except while paused because that's broken on Discord's end.

I've restarted the script and the issue seems to have gone away, I will keep an eye on it.

> I believe the progress bar is disappearing only for yourself. The same thing happens to me with my script. Pause your media and ask someone else if they can see your progress bar.

You're right, again! I logged into my other account to see what happens and when I pause YT Music it shows the broken time instead of the bar or blank as it appears to me, same as your code.

I guess we're just at the mercy of Discord then, if and when they decide to fix the bug instead of just releasing more overpriced avatar decorations!
