### ISSUE TITLE
Label on artist icon wrong when track artist isn't album artist

### ISSUE THREAD

**Issue by rumpff** [phin05/discord-rich-presence-plex#105]
When playing music the artist icon displays the picture of the album artist, but hovering over it shows the name of the track artist. 
This mismatch can happen when an album is for example a compilation or soundtrack and the album artist is various artists, like here:

![image](https://github.com/user-attachments/assets/eb81a69e-6f2e-457d-885b-a15057cd2491)

Since only album artists, and not track artists necessarily,  are stored in the plex db I think it's better to have it display the album artist rather than trying to force the picture of the track artist.

**Comment by phin05** [comment]
Changed in [v2.11.0](https://github.com/phin05/discord-rich-presence-plex/releases/tag/v2.11.0). The album artist's name will be displayed while hovering over that image.
