### ISSUE TITLE
Unable to modify the config file.

### ISSUE THREAD

**Issue by jackmeat** [phin05/discord-rich-presence-plex#107]
Whenever I modify the config file to add my imgur ID and an IMDB button (straight from the example provided minus me changing it to MY actual imgur ID) and save it, when I start the script again to reflect the new input, it recreates the config file from scratch and starts me over. There is still a modified version of the config with my changes, but now it is named config-1729159209.yaml in the data directory along with the newly created default config.yaml
This is on Windows 11, I checked the permissions on both files and they are identical, I have tried renaming the modified file back to config.yaml, and still it just creates a new blank one and retains the modified copy.

Looking forward to hearing what stupid mistake I am making this time :)

**Comment by phin05** [comment]
What you're describing happens when the config file can't be parsed due to something like a syntax error.

In your console output, you would see "Failed to parse the config file. A new one will be created", followed by the error thrown by the YAML module at the end, which would indicate what's wrong with your config file. What do you see?

**Comment by jackmeat** [comment]
I never took notice of what you are describing so I made sure to manually start the script so I could read the console. It points out the line the problem is on (17) which is in adding the button. I removed that entry and the imgur portion is working fine. From this point, I should be able to figure out the button problem or just not use it. I had to remove this to get it to parse properly.
- label: "{title} on IMDb"
      url: dynamic:imdb

I had it verbatim to the example but it doesn't seem to work:
buttons:
    - label: "{title} on IMDb"
      url: dynamic:imdb
    - label: Music Stats
      url: https://github.com
      mediaTypes:
        - track
I went ahead and copied the whole buttons section from the example but I get this.
 File "C:\Users\jackmeat\AppData\Local\Programs\Python\Python312\Lib\site-packages\yaml\parser.py", line 392, in parse_block_sequence_entry
    raise ParserError("while parsing a block collection", self.marks[-1],
yaml.parser.ParserError: while parsing a block collection
  in "data\config.yaml", line 17, column 6
expected <block end>, but found '<block mapping start>'
  in "data\config.yaml", line 18, column 7

I would like to get that IMDB button in there, don't much care about the music stats part. But I Just cannot seem to get the right input for that.. But thank you for at least getting the info in front of me so I know where to look.

**Comment by phin05** [comment]
Your indentation/spacing is not correct.

Make sure that it's exactly as specified in the example:

```yaml
  buttons:
    - label: "{title} on IMDb"
      url: dynamic:imdb
```

2 spaces before `buttons:`
4 spaces before `- label: "{title} on IMDb"`
6 spaces before `url: dynamic:imdb`

https://yaml.org/spec/1.2.2/#61-indentation-spaces

**Comment by jackmeat** [comment]
Ok, I see where it was faltering. When I copy/pasted, it screwed up that spacing and I did not go back and verify it against what it looked like compared to how it was written in the example. Thank you, I just did the same again but put the proper spacing in as you outlined and it worked properly. Thanks again for your patience.
