### ISSUE TITLE
Docker Issues

### ISSUE THREAD

**Issue by GreatArgorath** [phin05/discord-rich-presence-plex#109]
Sorry if this is the wrong place, asking here is a last resort after reading through previous issues and docker documentation for hours.

Very new to Linux and Docker, used this script on Windows for a while and loved it, recently switched to Linux and wanted to use it here too, but can't figure out what I'm doing.

I think I've got it running? It's connected to my Plex server and the logs show it's getting the right information, but I cannot figure out how to get Discord to see this, or how to configure this at all from here. I've tried to follow the readme but as I said, I'm very new to all of this so it doesn't make much sense to me. Any help would be appreciated.

**Comment by phin05** [comment]
Since you've got it running already, I assume you managed to figure out Docker Compose and are running it through that. Let me know if this is not the case.

Copying the compose file contents from the [example in the README](https://github.com/phin05/discord-rich-presence-plex?tab=readme-ov-file#docker-compose-example) should work in most cases. The 3 lines that might require changing are:

* `DRPP_UID: 1000` - Replace `1000` with your UID (user ID), which you can find by running the `id` command in your terminal.
* `DRPP_GID: 1000` - Replace `1000` with your GID (group ID), which you can find by running the `id` command in your terminal.
* `- /run/user/1000:/run/app` - Replace `/run/user/1000` with the path to your runtime directory, which you can find by running `echo $XDG_RUNTIME_DIR` in your terminal.

**Comment by GreatArgorath** [comment]
Yes, I've got it running through Compose, and all those settings from the example in the readme are correct for my system.

I get a "Discord IPC pipe not found" error, which I'm guessing is the issue, and I don't get any [WRITE] or [READ} messages.

```
[18-11-2024 04:13:45 PM] [ERROR] Discord IPC pipe not found (attempted pipes: /run/app/discord-ipc-0, /run/app/app/com.discordapp.Discord/discord-ipc-0, /run/app/.flatpak/com.discordapp.Discord/xdg-run/discord-ipc-0, /run/app/discord-ipc-1, /run/app/app/com.discordapp.Discord/discord-ipc-1, /run/app/.flatpak/com.discordapp.Discord/xdg-run/discord-ipc-1, /run/app/discord-ipc-2, /run/app/app/com.discordapp.Discord/discord-ipc-2, /run/app/.flatpak/com.discordapp.Discord/xdg-run/discord-ipc-2, /run/app/discord-ipc-3, /run/app/app/com.discordapp.Discord/discord-ipc-3, /run/app/.flatpak/com.discordapp.Discord/xdg-run/discord-ipc-3, /run/app/discord-ipc-4, /run/app/app/com.discordapp.Discord/discord-ipc-4, /run/app/.flatpak/com.discordapp.Discord/xdg-run/discord-ipc-4, /run/app/discord-ipc-5, /run/app/app/com.discordapp.Discord/discord-ipc-5, /run/app/.flatpak/com.discordapp.Discord/xdg-run/discord-ipc-5, /run/app/discord-ipc-6, /run/app/app/com.discordapp.Discord/discord-ipc-6, /run/app/.flatpak/com.discordapp.Discord/xdg-run/discord-ipc-6, /run/app/discord-ipc-7, /run/app/app/com.discordapp.Discord/discord-ipc-7, /run/app/.flatpak/com.discordapp.Discord/xdg-run/discord-ipc-7, /run/app/discord-ipc-8, /run/app/app/com.discordapp.Discord/discord-ipc-8, /run/app/.flatpak/com.discordapp.Discord/xdg-run/discord-ipc-8, /run/app/discord-ipc-9, /run/app/app/com.discordapp.Discord/discord-ipc-9, /run/app/.flatpak/com.discordapp.Discord/xdg-run/discord-ipc-9)
```

**Comment by phin05** [comment]
1. Post the contents of your compose file here. I'll take a look at it just in case you missed something.

2. Which Linux distro are you using?

3. Are you using the official Discord client? If so, where did you acquire/install it from?

**Comment by GreatArgorath** [comment]
1: 
```
services:
  drpp:
    container_name: drpp
    image: ghcr.io/phin05/discord-rich-presence-plex:latest
    restart: unless-stopped
    environment:
      DRPP_UID: 1000
      DRPP_GID: 1000
    volumes:
      - ./data:/app/data
      - /run/user/1000:/run/app
```
2. Fedora KDE 41

3. Yes, from Flathub

**Comment by phin05** [comment]
Run this command while Discord is running: `find /run -name discord-ipc-*`

Any results?

**Comment by GreatArgorath** [comment]
```
find: ‘/run/user/1000/doc’: Permission denied
/run/user/1000/.flatpak/com.discordapp.Discord/xdg-run/discord-ipc-0
/run/user/1000/app/com.discordapp.Discord/discord-ipc-0
find: ‘/run/user/1000/2cc871a7_87a8_48f6_b7b3_3ebb7842ecf0’: Permission denied
/run/user/1000/discord-ipc-0
```
I'm guessing it's a flatpak permissions issue then?

**Comment by phin05** [comment]
The permission issues there are unrelated.

It's strange that the `discord-ipc-0` file exists in 3 places. The `/run/user/1000/discord-ipc-0` one should exist if you were using the regular version of Discord instead of the Flatpak version, and with the Flatpak version, only one of the other two should exist.

Regardless of that, the script wasn't able to see any of them at all as per the error in the container logs. Did you add/modify/fix the `/run/user/1000:/run/app` part of the compose file under volumes after the creation of the container? If so, did you re-create the container after that by running `docker compose up -d` again?

**Comment by GreatArgorath** [comment]
I think something had gotten messed up with my discord install at some point, I've cleaned it up now and gotten a fresh install from flathub, but script still can't see it.

I didn't modify the compose file at all from the version in the readme.

**Comment by phin05** [comment]
Hmm, I'm not sure what's going on. Try re-creating the container anyways by running `docker compose down` and then `docker compose up -d`. If it's still not working, run `docker exec drpp find /run -name discord-ipc-*` and let me know the output, to check if the Discord IPC Unix socket file is visible inside the container.

**Comment by GreatArgorath** [comment]
Recreating it didn't fix it, and there's no output from running the second command.

**Comment by phin05** [comment]
What's the output of `docker inspect drpp --format '{{json .Mounts}}'`?

**Comment by GreatArgorath** [comment]
```
[{"Type":"bind","Source":"/host_mnt/home/argorath/Desktop/drpp/data","Destination":"/app/data","Mode":"rw","RW":true,"Propagation":"rprivate"},{"Type":"bind","Source":"/run/user/1000","Destination":"/run/app","Mode":"rw","RW":true,"Propagation":"rprivate"}]
```

**Comment by phin05** [comment]
The error from the logs you sent above (https://github.com/phin05/discord-rich-presence-plex/issues/109#issuecomment-2483504441), that's the only error you're seeing, right? Or are there any other errors?

**Comment by GreatArgorath** [comment]
Yes, that's the only error.

**Comment by phin05** [comment]
Everything looks right to me so I'm not sure what's happening. The runtime directory is mounted into the container according to the output of the inspect command but somehow the `discord-ipc-0` file which is in that directory is not showing up inside the container.

If you want, you can add me on Discord (username: phin05) and we can try to debug it a bit more with maybe screenshots or screen sharing or some more back-and-forth command running.

**Comment by phin05** [comment]
The issue was caused due to the usage of Docker Desktop, which runs containers inside a virtual machine, isolated from DIscord which runs on the host machine. Using normal Docker resolved the issue.
