### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by JihadiJackass** [phin05/discord-rich-presence-plex#23]
Hey, I'm not to keen on how python works and whatnot, I used one of these previously but it wasn't so complicated then or confusing.

Just curious how to set this up, I don't understand what the websocket-client is, or what to do with it; same with the plexapi.

I don't recall using either of those previously on whatever script I had used, it may even be this one? I don't know.

Could I possibly have a bit better explanation on how something like this would be setup?

**Comment by jacobmix** [comment]
Explained how to set it up step by step here: https://github.com/Phineas05/discord-rich-presence-plex/issues/20#issuecomment-625757212

**Comment by phineas05** [comment]
You can try setting it up by following the updated basic installation instructions in the [README](https://github.com/phineas05/discord-rich-presence-plex/blob/master/README.md).
