### ISSUE TITLE
[REQUEST] New "Free" Movies from PLEX

### ISSUE THREAD

**Issue by HQv2** [phin05/discord-rich-presence-plex#24]
PLEX now offers free movies and TV shows for streaming, but they do not show up on Discord when watching them. Would this be possible?

Info: https://www.plex.tv/watch-free/

Thank you!

**Comment by FinalDoom** [comment]
I'm guessing the location of this play data is similar to the VOD sections, and Podcasts, TIDAL, etc. It'd be nice to be able to report those as well. I'm specifically interested in Podcasts, but this seems like it'd be similar so didn't want to open a different issue.

**Comment by phin05** [comment]
There doesn't seem to be any way to get information about movies, shows, live TV or music offered directly by Plex being played on other sessions so I'm closing this issue for now.
