### ISSUE TITLE
[REQUEST] Music video support

### ISSUE THREAD

**Issue by jacobmix** [phin05/discord-rich-presence-plex#27]
Can support for music videos be added?
Right now i just get this error:
`onPlexServerAlert Error: Unknown library type <Video type='clip'../>`

To get a music video to show up they have to follow [this](https://support.plex.tv/articles/205568377-adding-local-artist-and-music-videos/)
Aka: Make sure the album artist isn't "Various Artists", and just name as normal with `-video` at the end.
They show up under Album Artist, and you can't edit anything about them in Plex.
If you already have just the audio file of it, the track will get a monitor icon.

**Comment by superboo07** [comment]
I'd also like support for this, I think it'd be a very nice feature since this script is pretty much perfect in all other ways.

**Comment by phin05** [comment]
Implemented in [v2.6.0](https://github.com/phin05/discord-rich-presence-plex/releases/tag/v2.6.0).
