### ISSUE TITLE
Two factor authentication

### ISSUE THREAD

**Issue by ronilaukkarinen** [phin05/discord-rich-presence-plex#39]
How to set up this with account that has 2FA enabled?

**Comment by jacobmix** [comment]
For Plex right? Just use your Plex token. Discord shouldn't matter as it connects to the Discord already logged in on the same PC.
If you need help on how to setup the program in general this covers most you need to know: https://github.com/phineas05/discord-rich-presence-plex/issues/20#issuecomment-625757212
