### ISSUE TITLE
Issue running in background on macOS

### ISSUE THREAD

**Issue by hotsno** [phin05/discord-rich-presence-plex#43]
Running this script in the background isn't working for me on macOS.

On macOS (and Linux) you're able to run commands in the background with `&` and then detach them from the terminal instance with `disown`. So the command I used is `python3 main.py & disown`. After doing this I get 1 line of output (`[21-05-2022 08:43:26 PM] [INFO] Discord Rich Presence for Plex - v2.2.2`) and then nothing else. When I play something in Plex, the RPC doesn't show up, so I'm guessing the script either isn't running or is failing. I do see the `main.py` process in the output of `ps -ax | grep Python`, however I'm not sure what I can conclude from this this. Trying this same command (` & disown`) with a simple test Python script that just prints something every 2 seconds, output is generated every 2 seconds until I kill the process.

<details>
<summary>Workaround</summary>
<br>

Here's a hacky workaround I use for this issue on macOS that creates a `tmux` session that runs the script every time the computer wakes up from sleep:
1. Install [Homebrew](https://brew.sh/)
2. Install [SleepWatcher](https://www.bernhard-baehr.de/): `brew install sleepwatcher`
3. Install tmux: `brew install tmux`
4. Create `start_plex_presence` script somewhere like `~/.local/bin`
```bash
#!/bin/bash

PATH_TO_DISCORD_RICH_PRESENCE_PLEX="/change/me"
SESSION_NAME="plex-presence"

if tmux has-session -t $SESSION_NAME 2>/dev/null; then
	tmux kill-session -t $SESSION_NAME
fi

COMMAND="cd $PATH_TO_DISCORD_RICH_PRESENCE_PLEX; zsh -c 'python3 main.py; zsh'"

tmux new-session -d -s $SESSION_NAME "$COMMAND"
```
5. Make script executable: `chmod +x /path/to/script`
6. Create `~/.wakeup`
```bash
#!/bin/bash

/path/to/script
```
7. Make this executable just in case: `chmod +x ~/.wakeup`
8. Run `brew services start sleepwatcher`

I might've missed something but I've gotten it to work perfectly fine. I'd recommend learning at least the basics of tmux as well if you use this.

</details>

**Comment by phineas05** [comment]
I have just committed a fix. Update your version of the script and let me know if the issue is fixed.

**Comment by akulakovsky** [comment]
Thanks for the quick fix and response!

`pythonw main.py` works on Windows now. I tried on macOS and it's still doing the same thing. I turned on logging to file and only this line shows up:
`[21-05-2022 10:30:29 PM] [INFO] Discord Rich Presence for Plex - v2.2.3`

**Comment by hotsno** [comment]
Thanks for the quick fix and response! `pythonw main.py` works on Windows now. 

I tried on macOS and it's still doing the same thing. I turned on logging to file and only this line shows up:
[21-05-2022 10:30:29 PM] [INFO] Discord Rich Presence for Plex - v2.2.3

**Comment by phineas05** [comment]
I've made a couple changes to try to debug it. Update your copy of the script again and see if anything more gets logged.

**Comment by hotsno** [comment]
Now I get 2 lines of output:
```
[22-05-2022 10:47:49 AM] [INFO] Discord Rich Presence for Plex - v2.2.4
[22-05-2022 10:47:49 AM] [INFO] [laptop/CD933] Signing into Plex
```
And the RPC doesn't seem to be working (when using ` & disown`).

**Comment by phineas05** [comment]
It appears to be freezing on this line after the "Signing into Plex" message:
```python
self.account = MyPlexAccount(token = self.token)
```
I'm not sure what the issue is since `MyPlexAccount` is imported from the PlexAPI module which is out of my control. I don't see any reason for it to act differently while the script is running in the background. I'm on Windows so I'm unable to test this on macOS.

**Comment by GhislainSamy** [comment]
personally I use a scheduled task :

start.cmd : 

echo off
c:
cd C:\discord-rich-presence-plex-master
start plex_rich_presence-noconsole.vbs
exit


plex_rich_presence-noconsole.vbs : 

strCommand = "cmd /c python main.py"

For Each Arg In WScript.Arguments
    strCommand = strCommand & " """ & replace(Arg, """", """""""""") & """"
Next

CreateObject("Wscript.Shell").Run strCommand, 0, false

cordially

**Comment by GhislainSamy** [comment]
personally in Windows I use a scheduled task :

in scheduler when starting the computer : start.cmd :

echo off
c:
cd C:\discord-rich-presence-plex-master
start plex_rich_presence-noconsole.vbs
exit

plex_rich_presence-noconsole.vbs :

strCommand = "cmd /c python main.py"

For Each Arg In WScript.Arguments
strCommand = strCommand & " """ & replace(Arg, """", """""""""") & """"
Next

CreateObject("Wscript.Shell").Run strCommand, 0, false

==
cordially

**Comment by GreenglassT** [comment]
When using `ctrl+z` to suspend the script, then using `bg`, the script does not start up again and update the rich presence in Discord. It just continues to use the last updated information. (e.g. Shows old song even after new song is played)

**Comment by zeroquinc** [comment]
On Windows I run it in the background by renaming main.py to main.pyw. Then just make a shortcut out of it and place this shortcut in your Startup folder. You can do this by opening Run with Win+R and then type `shell:startup`. Works on every version of Windows for me with a basic Python install.

**Comment by TsunaSetsu** [comment]
> On Windows I run it in the background by renaming main.py to main.pyw. Then just make a shortcut out of it and place this shortcut in your Startup folder. You can do this by opening Run with Win+R and then type `shell:startup`. Works on every version of Windows for me with a basic Python install.

I tried using your method but this shows up on my console.txt 

[29-10-2023 11:16:19 PM] [INFO] Discord Rich Presence for Plex - v2.3.4
[29-10-2023 11:16:19 PM] [INFO] [myServer/69AA2] Signing into Plex
[29-10-2023 11:16:19 PM] [ERROR] An unexpected error occured
Traceback (most recent call last):
  File "C:\discord-rich-presence-plex\main.pyw", line 65, in <module>
    if sys.stdin.isatty():
       ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'isatty'

**Comment by phin05** [comment]
@TsunaSetsu That issue should be fixed now. Try the new version (2.3.5).

**Comment by GhislainSamy** [comment]
Actually on my Windows 11 : 

Scheduled Task : 
Start a program : "C:\discord-rich-presence-plex\start_plex_rich_presence.cmd"

start_plex_rich_presence.cmd : 
```
cd C:\discord-rich-presence-plex
start pythonw main.py
```

Test : OK

**Comment by phin05** [comment]
I'm closing this as stale.

Feel free to post a comment if you are still facing this issue, after testing again using the latest version.

**Comment by hotsno** [comment]
It's still happening, I actually just started using this project again a few days ago :) I updated the post with a workaround I'm using.

**Comment by phin05** [comment]
You tried v2.6.0? It still freezes after the "Signing into Plex" line?

**Comment by hotsno** [comment]
So I decided to ask ChatGPT and I think it found the issue lol: https://chat.openai.com/share/0ab59919-d751-41f4-adad-bda038a7f855

The issue no longer happens with `python3 main.py </dev/null & disown`

As you said before, it seems to be out of this project's control and is an issue in the Python Plex API. [Here's](https://github.com/pkkid/python-plexapi/blob/b51aa1924b5b28ba61aefbb4162aff6e6864561b/plexapi/myplex.py#L119) a starting point for where to look, but I'm satisfied with the solution above.
