### ISSUE TITLE
Can not run script with nohub

### ISSUE THREAD

**Issue by Matth3wW** [phin05/discord-rich-presence-plex#61]
When running the script via nohup on Kubuntu 22.10 with python 3.10.7, the script crashes.

Here is how I am executing the script:

`nohup python3 /home/matthew/.discord-rich-presence-plex-master/main.py > Output.txt 2>&1 &`

Output.txt contains the following:

```
[28-11-2022 03:00:19 PM] [INFO] Discord Rich Presence for Plex - v2.3.2
[28-11-2022 03:00:19 PM] [INFO] [WoodwardMC/C18F8] Signing into Plex
[28-11-2022 03:00:19 PM] [ERROR] An unexpected error occured
Traceback (most recent call last):
  File "/home/matthew/.discord-rich-presence-plex-master/main.py", line 53, in <module>
    userInput = input()
OSError: [Errno 9] Bad file descriptor
```

Commenting out the following lines allows the script to be ran in nohup

```
	plexAlertListeners = [PlexAlertListener(user["token"], server) for user in config["users"] for server in user["servers"]]
#	if sys.stdin:
#		while True:
#			userInput = input()
#			if userInput in ["exit", "quit"]:
#				raise KeyboardInterrupt
#	else:
	while True:
		time.sleep(3600)
```

I know very little about programming, so I'm unsure why this is the case. Can someone more familiar with python help explain why this is?

**Comment by phin05** [comment]
Can you try [v2.3.4](https://github.com/phin05/discord-rich-presence-plex/releases/tag/v2.3.4)? The issue should be fixed.

**Comment by Matth3wW** [comment]
> Can you try [v2.3.4](https://github.com/phin05/discord-rich-presence-plex/releases/tag/v2.3.4)? The issue should be fixed.

I can confirm it is fixed. Thank you!
