### ISSUE TITLE
letterboxd

### ISSUE THREAD

**Issue by Darotondo** [phin05/discord-rich-presence-plex#68]
Is there a way to change the dynamic link from say tmdb to use a letterboxd link

**Comment by zluckytraveler** [comment]
IDK how well that will work, since Letterboxd database doesn't hold the majority of Television series, so there will be a high percentage of unmatched id numbers.

**Comment by phin05** [comment]
Implemented in [v2.6.0](https://github.com/phin05/discord-rich-presence-plex/releases/tag/v2.6.0).

Use `dynamic:letterboxd`. Only works for movies.
