### ISSUE TITLE
Can this tool also set a custom status text instead of "Playing Plex"?

### ISSUE THREAD

**Issue by thetigeregg** [phin05/discord-rich-presence-plex#73]
Can this tool be used or updated to change my user's custom status text? Such that instead of displaying "Playing Plex", it will display a music note:
<img width="166" alt="image" src="https://github.com/phin05/discord-rich-presence-plex/assets/111239332/4b9f437f-1f4d-4a23-a477-7b477666ac90">
->
<img width="167" alt="image" src="https://github.com/phin05/discord-rich-presence-plex/assets/111239332/fe83b50c-7b41-4781-af94-cc8dbd435044">

I currently manually change that custom status text like so:
<img width="427" alt="image" src="https://github.com/phin05/discord-rich-presence-plex/assets/111239332/3e64382b-1020-40b6-9b01-26036dd146bf">

I believe the "Plex" text comes from the Discord Developer Application name that we all connect to? If so, would a possible workaround be creating my own Application with my desired name, and changing the client id that this tool points to?

**Comment by phin05** [comment]
Unfortunately, this isn't possible without breaking Discord ToS. See https://github.com/phin05/discord-rich-presence-plex/issues/33#issuecomment-1123555125.

You can also refer to https://discord.com/developers/docs/game-sdk/activities#data-models-activitytype-enum where the custom activity type is documented, and it says the following:

> ActivityType is strictly for the purpose of handling events that you receive from Discord; though the SDK/our API will not reject a payload with an ActivityType sent, it will be discarded and will not change anything in the client.

**Comment by phin05** [comment]
> I believe the "Plex" text comes from the Discord Developer Application name that we all connect to? If so, would a possible workaround be creating my own Application with my desired name, and changing the client id that this tool points to?

You can do that, but it won't remove the "Playing" part.

**Comment by phin05** [comment]
Discord allows changing the activity type now. Implemented in [v2.8.0](https://github.com/phin05/discord-rich-presence-plex/releases/tag/v2.8.0).
