### ISSUE TITLE
Album Art not appearing

### ISSUE THREAD

**Issue by JBloom91** [phin05/discord-rich-presence-plex#74]
I went ahead and followed the instructions for Obtaining an Imgur client ID, but album art still does not display. I am rather new to these sort of things, so if it's user error on my part I apologize.

**Comment by phin05** [comment]
In your config file, have you set `posters.enabled` to `true` and `posters.imgurClientID` to your client ID? Are there any messages related to images in the console?

**Comment by phin05** [comment]
I'm closing this as stale.

Feel free to post a comment along with console logs if you are still facing this issue after checking what I mentioned above.
