### ISSUE TITLE
Incorrect ownership of runtime directory created by Docker - systemd `user@1000.service` breaks after reboot when keeping docker compose runnig in the background

### ISSUE THREAD

**Issue by jackra1n** [phin05/discord-rich-presence-plex#77]
After changes from 46593378d9573d43a843def2191eeae96ec38451 I tried using docker again as it didnt work for me before and this time it started working.
The problem is that after rebooting my system while the container is running the system will break. I first noticed it that I didn't have any audio input/output devices, some startup apps werent active, long delays after keyboard shortcuts.
I tried to find out what the problem is and what I found out is that `/run/user/1000` has wrong owner after reboot while the docker container is running. The `root` user is owner of it.
Here some screenshots
![image](https://github.com/phin05/discord-rich-presence-plex/assets/45038833/ed3d30e4-ba1b-4a73-a6a3-b298c9cafe83)
![image](https://github.com/phin05/discord-rich-presence-plex/assets/45038833/c56c92fb-4d15-4f69-be44-4d7ac9070b0b)
![image](https://github.com/phin05/discord-rich-presence-plex/assets/45038833/7a7ac835-3532-4e2c-9f89-fa02f59f1fa2)
![2024-02-02_12-09](https://github.com/phin05/discord-rich-presence-plex/assets/45038833/b2231c16-820e-4a1c-9cc4-791d09e7ecf3)

**Comment by phin05** [comment]
I don't see how this could happen unless you accidentally mounted `/run/user/1000` into the container as `/app/data` instead of `/run/app`.

What does your Docker Compose file / `docker run` command look like?

**Comment by jackra1n** [comment]
Oh sorry, forgot about it.
```yaml
version: "3.8"

services:
  drpp:
    container_name: drpp
    image: ghcr.io/phin05/discord-rich-presence-plex:latest
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - /run/user/1000/app/com.discordapp.Discord:/run/app:ro
```
this is what my compose.yaml looks like

**Comment by phin05** [comment]
Those volume mounts wouldn't cause this. The container wouldn't even be able to access `/run/user/1000` and wouldn't be able to change that directory's ownership.

Did you run it in any different way other than that Compose configuration?

The only directory the script changes ownership for is `/app` inside the container. So unless you mistakenly mounted `/run/user/1000` as `/app` or `/app/data`, something else must have caused this.

**Comment by phin05** [comment]
The ownership doesn't change if you reboot while the container is not active?

**Comment by phin05** [comment]
Could you test it again exactly as below?

Scenario 1:

1. Run `docker compose down`
2. Ensure proper ownership by running `chown -R 1000:1000 /run/user/1000`
3. Run `docker compose up -d`
4. Verify ownership of `/run/user/1000`
5. Reboot
6. Verify ownership again

Scenario 2:

1. Run `docker compose down`
2. Ensure proper ownership by running `chown -R 1000:1000 /run/user/1000`
3. Run `docker compose up -d`
4. Verify ownership of `/run/user/1000`
5. Run `docker compose down`
6. Verify ownership again
7. Reboot
8. Verify ownership again

At which point does the ownership change in both scenarios?

**Comment by jackra1n** [comment]
Both cases starting from desktop of a working, rebooted system (no drpp running):

Scenario 1:
- Run `docker compose down` :white_check_mark:
- Ensure proper ownership by running `chown -R 1000:1000 /run/user/1000` :white_check_mark:
- Run `docker compose up -d` :white_check_mark:
- Verify ownership of `/run/user/1000` :white_check_mark: -> Still owned by 1000
- Reboot :white_check_mark: 
- Verify ownership again -> Now owned by root 
![image](https://github.com/phin05/discord-rich-presence-plex/assets/45038833/e74305c0-26d6-415e-9c3e-a3c72eb6b66d)

Scenario 2:

- Run `docker compose down` :white_check_mark:
- Ensure proper ownership by running `chown -R 1000:1000 /run/user/1000` :white_check_mark:
- Run `docker compose up -d` :white_check_mark:
- Verify ownership of `/run/user/1000` :white_check_mark: -> Still owned by 1000
- Run `docker compose down` :white_check_mark:
- Verify ownership again :white_check_mark: -> Still owned by 1000
- Reboot :white_check_mark:
- Verify ownership again :white_check_mark: -> Still owned by 1000

**Comment by phin05** [comment]
I realise what's happening now. `/run` is a temporary filesystem which is empty on boot. The Docker service starts before user signin since it's a system service. `/run/user/1000` doesn't exist at that point. This causes the Docker service, which runs as root, to create the directory by itself because it has to mount it into the container.

I'll try to think of a proper solution, but for now, add this to your Docker Compose file for the `drpp` container and test it again:
```
entrypoint: sh -c "chown -R 1000:1000 /run/app && python main.py"
```

**Comment by jackra1n** [comment]
Hmmm. I just tried that and still seems to fail.
Container not running (removed) -> Edit compose.yaml -> start container -> reboot
![image](https://github.com/phin05/discord-rich-presence-plex/assets/45038833/7fa504ba-43dd-4155-99fe-19ad8adafc83)

**Comment by phin05** [comment]
Right, that doesn't work for you because `/run/app` is `/run/user/1000/app/com.discordapp.Discord` instead of `/run/user/1000` since that's what the Flatpak version uses, so the `chown` is happening on only that instead of the whole `/run/user/1000` tree.

This would have been easier if there was a way to specify the owner of directories newly created by Docker during mounting. I'll implement some sort of workaround and get back to you later.

**Comment by phin05** [comment]
Change your Compose file as below:

```yaml
services:
  drpp:
    container_name: drpp
    image: ghcr.io/phin05/discord-rich-presence-plex:latest
    restart: unless-stopped
    environment:
      DRPP_UID: 1000
      DRPP_GID: 1000
    volumes:
      - ./data:/app/data
      - /run/user/1000:/run/app
```

Run `docker compose up -d --pull always` to pull and run the updated container image (v2.4.5) and see if the issue is fixed.

**Comment by jackra1n** [comment]
Hi
Sorry for the long wait! I was on holidays.
Just updated my compose and the image to the newest version (2.7.0) and it seems to be working fine!
Thank you very much
