### ISSUE TITLE
Reducing the size of the covers before upload

### ISSUE THREAD

**Issue by WSADKeysGaming** [phin05/discord-rich-presence-plex#78]
The current implementation of this tool uploads the raw image from Plex to Imgur as far I am aware, except for the conversion of JPEG -> JPG for compatibilty. I save very high quality artwork to my Plex library [(see this 6000x6000 Bruce Springsteen cover)](https://a5.mzstatic.com/us/r1000/0/Music115/v4/32/72/68/327268ba-b9dd-b322-2a16-bdd0212df48c/074643865326.jpg) and it takes a fairly significant time to upload on my connection before drpp is able to update the info on Discord. Is it possible to reduce the size of the covers to all, say, 256x256 JPGs before being uploaded to Imgur? Even on mobile, the image takes up a very small portion of the screen. All of this extra data, on my super-meticulous mega covers or even just the ones provided by Plex, is a waste in my opinion.

**Comment by phin05** [comment]
Implemented in [v2.5.0](https://github.com/phin05/discord-rich-presence-plex/releases/tag/v2.5.0).
