### ISSUE TITLE
[feature request] musicbrainz dynamic url

### ISSUE THREAD

**Issue by rumpff** [phin05/discord-rich-presence-plex#79]
musicbrainz is like the tmdb for music, and plex uses it for music metadata. it would be nice to have it available as a dynamic url option.

tautulli is able to show musicbrainz links when enabling Rich Metadata Info for notifications, so I would assume the matched release id is exposed somewhere

**Comment by phin05** [comment]
Implemented in [v2.6.0](https://github.com/phin05/discord-rich-presence-plex/releases/tag/v2.6.0).

Use `dynamic:musicbrainz`.
