### ISSUE TITLE
[Feature Request] dynamic button labels

### ISSUE THREAD

**Issue by rumpff** [phin05/discord-rich-presence-plex#80]
have information about what you're watching/listening to in the button label

example: `-label: "{movie_title} on letterboxd"`

since buttons can only contain up to 32 characters there might need to be some automatic truncation if the string gets too large

**Comment by phin05** [comment]
Implemented in [v2.7.0](https://github.com/phin05/discord-rich-presence-plex/releases/tag/v2.7.0).

Use `{title}` in your label.
