### ISSUE TITLE
[Enhancement] Add "Watching" to status

### ISSUE THREAD

**Issue by Permanently** [phin05/discord-rich-presence-plex#81]
Simply, add "Watching Plex" instead of "Playing Plex" on the Discord status. [There are docs on this here](https://discord.com/developers/docs/game-sdk/activities#data-models-activitytype-enum).

**Comment by phin05** [comment]
This isn't possible . See the message on that page below the table you linked to:

"ActivityType is strictly for the purpose of handling events that you receive from Discord; though the SDK/our API will not reject a payload with an ActivityType sent, **it will be discarded and will not change anything in the client**."

https://github.com/phin05/discord-rich-presence-plex/issues/33#issuecomment-1123555125
https://github.com/phin05/discord-rich-presence-plex/issues/73#issuecomment-1830542353

**Comment by phin05** [comment]
Discord allows changing the activity type now. Implemented in [v2.8.0](https://github.com/phin05/discord-rich-presence-plex/releases/tag/v2.8.0).
