### ISSUE TITLE
Option to stop displaying Discord activity when playback is paused

### ISSUE THREAD

**Issue by Tazzle973** [phin05/discord-rich-presence-plex#87]
Hello,

Would it be possible to add an option to stop displaying activity when media is paused?

In my use case, when I pause my music to start watching a video, the activity on Discord switches between playing the video and playing the music even though the latter is paused.

Best regards.

**Comment by phin05** [comment]
Implemented in [v2.8.0](https://github.com/phin05/discord-rich-presence-plex/releases/tag/v2.8.0).

Controlled by the `display.paused` config field, which is `false` by default.
