### ISSUE TITLE
Album Artwork Through imgur?

### ISSUE THREAD

**Issue by SammBrooks** [phin05/discord-rich-presence-plex#89]
Hia. 
Using this plugin specifically for Plexamp as I don't use Plex for my Movies/TV.
I was curious if the imgur method works for Album Covers same as it does for Posters.

Considering I'm just a casual user of open-source programs (and don't have imgur to begin with) I would rather not go through the effort of setting that up if it's not going to work or if there's an option that pulls the Album Art directly from Plex instead.

Thanks in advance.

**Comment by phin05** [comment]
Yes, album art will be pulled from Plex, uploaded to Imgur, and displayed on Discord.

**Comment by SammBrooks** [comment]
Fantastic! 
Thanks a bunch.
