### ISSUE TITLE
Feature request: Change "playing" to "watching" and switch "Plex" with a configurable string.

### ISSUE THREAD

**Issue by RenNagasaki** [phin05/discord-rich-presence-plex#90]
Hey,
I'd like to show what I'm watching but not where (Plex).
And I'd like to show it as Watching "Movie/Series/Anime" instead of Playing  "Movie/Series/Anime" 

Kind regards.

**Comment by phin05** [comment]
"Plex" can't be completely removed, but to change it, you'll have to create your own application at https://discord.com/developers/applications and use that application's ID [here](https://github.com/phin05/discord-rich-presence-plex/blob/5461ad20ed0172599e3a9d41cc0507811b3abe15/config/constants.py#L8). You can name the application what you want to be displayed. You'll also have to add the [app icon](https://cdn.discordapp.com/app-icons/413407336082833418/82d3bdb4139603368727d04da9ec9547.png) and the four required images under rich presence assets: [logo](https://cdn.discordapp.com/app-assets/413407336082833418/413413572194992129.png), [playing](https://cdn.discordapp.com/app-assets/413407336082833418/413414267618852866.png), [paused](https://cdn.discordapp.com/app-assets/413407336082833418/413414293112094730.png), [buffering](https://cdn.discordapp.com/app-assets/413407336082833418/413414325248589836.png).

Changing "playing" isn't possible. Refer to:
https://github.com/phin05/discord-rich-presence-plex/issues/33#issuecomment-1123555125
https://github.com/phin05/discord-rich-presence-plex/issues/73#issuecomment-1830542353
https://github.com/phin05/discord-rich-presence-plex/issues/81

**Comment by phin05** [comment]
Discord allows changing the activity type now. Implemented in [v2.8.0](https://github.com/phin05/discord-rich-presence-plex/releases/tag/v2.8.0).
