### ISSUE TITLE
Dynamic Activity Type

### ISSUE THREAD

**Issue by VaporyCoder** [phin05/discord-rich-presence-plex#92]
I think it would be cool if you could script out some kind of if/then or something and it will set the activity type based on whether you are "**Watching**" or "**Listening**" to something. 
Also the new RPC supports proper 9:16 images but I don't know if that is accessible or not
![Screenshot 2024-08-28 132246](https://github.com/user-attachments/assets/d780f4bc-754f-4ba0-a043-6a529aa96530)
![Screenshot 2024-08-28 132334](https://github.com/user-attachments/assets/2b091804-c9af-4e00-ba40-50dadc139339)

**Comment by phin05** [comment]
Implemented in [v2.8.0](https://github.com/phin05/discord-rich-presence-plex/releases/tag/v2.8.0).

> Also the new RPC supports proper 9:16 images but I don't know if that is accessible or not

Could you provide any additional information regarding this? The uncropped poster is being sent to Discord already, but there's no way to control how Discord displays the poster in a cropped view as far as I can tell.

**Comment by phin05** [comment]
> Also the new RPC supports proper 9:16 images but I don't know if that is accessible or not

Omitting the `small_image` seems to make it so that the `large_image` (poster) is displayed without getting cropped. Implemented in [v2.9.0](https://github.com/phin05/discord-rich-presence-plex/releases/tag/v2.9.0).
