### ISSUE TITLE
Current Time broken due to new Discord update

### ISSUE THREAD

**Issue by 5ynchrogazer** [phin05/discord-rich-presence-plex#93]
When playing Music or Movies, the current time is stuck to where you last paused and won't advance until you pause (or 0:00 when a new track is playing).

**Comment by phin05** [comment]
Fixed in [v2.8.0](https://github.com/phin05/discord-rich-presence-plex/releases/tag/v2.8.0).

Current time / elapsed time display should be fixed, but the alternative remaining time display (if `display.remainingTime` is enabled in config) is broken as of Discord version stable 323314 (48a671f).

**Comment by 5ynchrogazer** [comment]
Well, it it's broken on Discord's end, there's nothing much you can do :P
Thanks for the clarification :)
