### ISSUE TITLE
Cannot start main.py for the first time.

### ISSUE THREAD

**Issue by jackmeat** [phin05/discord-rich-presence-plex#95]
I seem to be stuck in a loop trying to run main.py for the first time (Windows 11 user)
C:\Tools\discord-rich-presence-plex>python main.py
[05-09-2024 05:03:40 PM] [ERROR] An unexpected error occured during automatic installation of dependencies. Install them manually by running the following command: python -m pip install -U -r requirements.txt
Traceback (most recent call last):
  File "main.py", line 32, in <module>
    def parsePipPackages(packagesStr: str) -> dict[str, str]:
TypeError: 'type' object is not subscriptable
Traceback (most recent call last):
  File "main.py", line 47, in <module>
    from core.config import config, loadConfig, saveConfig
  File "C:\Tools\discord-rich-presence-plex\core\config.py", line 5, in <module>
    import models.config
  File "C:\Tools\discord-rich-presence-plex\models\config.py", line 12, in <module>
    class Button(TypedDict):
  File "C:\Tools\discord-rich-presence-plex\models\config.py", line 15, in Button
    mediaTypes: list[str]
TypeError: 'type' object is not subscriptable

Simple enough instructions to install dependencies (which I ran the first time I saw the message above, this is what I get now) 
C:\Tools\discord-rich-presence-plex>python -m pip install -r requirements.txt
Requirement already satisfied: PlexAPI==4.15.16 in c:\users\jackmeat\appdata\local\programs\python\python38\lib\site-packages (from -r requirements.txt (line 1)) (4.15.16)
Requirement already satisfied: requests==2.32.3 in c:\users\jackmeat\appdata\local\programs\python\python38\lib\site-packages (from -r requirements.txt (line 2)) (2.32.3)
Requirement already satisfied: websocket-client==1.8.0 in c:\users\jackmeat\appdata\local\programs\python\python38\lib\site-packages (from -r requirements.txt (line 3)) (1.8.0)
Requirement already satisfied: PyYAML==6.0.2 in c:\users\jackmeat\appdata\local\programs\python\python38\lib\site-packages (from -r requirements.txt (line 4)) (6.0.2)
Requirement already satisfied: Pillow==10.4.0 in c:\users\jackmeat\appdata\local\programs\python\python38\lib\site-packages (from -r requirements.txt (line 5)) (10.4.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\jackmeat\appdata\local\programs\python\python38\lib\site-packages (from requests==2.32.3->-r requirements.txt (line 2)) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\jackmeat\appdata\local\programs\python\python38\lib\site-packages (from requests==2.32.3->-r requirements.txt (line 2)) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\jackmeat\appdata\local\programs\python\python38\lib\site-packages (from requests==2.32.3->-r requirements.txt (line 2)) (1.26.12)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\jackmeat\appdata\local\programs\python\python38\lib\site-packages (from requests==2.32.3->-r requirements.txt (line 2)) (2022.6.15.2)

C:\Tools\discord-rich-presence-plex>python --version
Python 3.8.3
C:\Tools\discord-rich-presence-plex>pip --version
pip 24.2 from C:\Users\jackmeat\AppData\Local\Programs\Python\Python38\lib\site-packages\pip (python 3.8)

So at this point, I am past my limited knowledge in what to do next.

**Comment by phin05** [comment]
Python 3.8.3 is not supported. Install Python version 3.10 or newer as specified in the installation instructions in the README.

**Comment by jackmeat** [comment]
Ah, that is 3.8.3 and it needs 3.10 (as in ten) I love asking dumb questions. It worked without issue so thank you.
