### ISSUE TITLE
Adding support for the new RPC progress bar

### ISSUE THREAD

**Issue by SerenModz21** [phin05/discord-rich-presence-plex#97]
In addition to all the new RPC changes that have been made recently, we can now use the progress bar that can be seen on official RPCs such as Spotify.

I have implemented this feature with an opt-in behaviour so that users can choose whether or not they want to use it.  My pull request for this can be found here: https://github.com/phin05/discord-rich-presence-plex/pull/98

An example showing it:
![mini-view](https://cdn.serenmodz.rocks/xpx-ORZZ.png)
![full-view](https://cdn.serenmodz.rocks/b9vCzc1l.png)

**Comment by phin05** [comment]
Implemented in [v2.10.0](https://github.com/phin05/discord-rich-presence-plex/releases/tag/v2.10.0).
